//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int assignmetId { get; set; }
        public string assignmentTitle { get; set; }
        public string assignmentDesc { get; set; }
        public Nullable<System.DateTime> assignmentCreatedDate { get; set; }
        public Nullable<System.DateTime> assignmentSubmissionDate { get; set; }
        public Nullable<int> assignmentUserId { get; set; }
        public Nullable<int> assignmentStatusId { get; set; }
    
        public virtual Statue Statue { get; set; }
        public virtual User User { get; set; }
    }
}
